-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    "verifyCode" character NOT NULL,
    password character NOT NULL,
    id integer NOT NULL,
    "emailAddress" character NOT NULL,
    verified boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.systemworkers
(
    id integer NOT NULL,
    "userId" integer NOT NULL,
    "systemWorkerName" character NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    "userId" integer NOT NULL,
    "companyName" character NOT NULL,
    "webSiteDomainName" character NOT NULL,
    "phoneNumber" character NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    id integer NOT NULL,
    "userId" integer NOT NULL,
    "typeofworksId" integer NOT NULL,
    "nationalityId" integer NOT NULL,
    "firstName" character NOT NULL,
    "lastName" character NOT NULL,
    "dateOfBirth" date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.typeofworks
(
    id integer NOT NULL,
    title character NOT NULL,
    description character NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.systemworkers
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY ("typeofworksId")
    REFERENCES public.typeofworks (id)
    NOT VALID;

END;