-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    name character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.coverletters
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    content character varying(255),
    jobseeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    company_name character varying(255),
    is_verified boolean,
    phone_number character varying(255),
    web_site_domain_name character varying(255),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employersverificationsystemworkers
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    system_worker_id integer NOT NULL,
    created_at date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.experiences
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    end_at date,
    "position" character varying(255),
    start_at date,
    working_place character varying(255),
    jobseeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.foreignlanguages
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    language character varying(255),
    level integer,
    jobseeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.images
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    url character varying(255),
    jobseeker_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobadverts
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    deadline date,
    description character varying(255),
    is_open boolean,
    open_position_count integer,
    published_at date,
    salary_max integer,
    salary_min integer,
    city_id integer,
    employer_id integer,
    type_of_work_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    date_of_birth date,
    first_name character varying(255),
    is_verified boolean,
    last_name character varying(255),
    nationality_id character varying(255),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.links
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    link_name character varying(255),
    url character varying(255),
    jobseeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.programmingskills
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    skill_name character varying(255),
    jobseeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.schools
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    department character varying(255),
    end_at date,
    school_name character varying(255),
    start_at date,
    jobseeker_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.systemworkers
(
    system_worker_name character varying(255),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.typeofworks
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    description character varying(255),
    title character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    email_address character varying(255),
    password character varying(255),
    PRIMARY KEY (id)
);

CREATE TABLE public.verificationcodes
(
    id integer NOT NULL,
    created_at date,
    is_active boolean,
    is_deleted boolean,
    code character varying(255),
    is_confirmed boolean,
    user_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE public.coverletters
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.experiences
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.foreignlanguages
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.images
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.jobadverts
    ADD FOREIGN KEY (type_of_work_id)
    REFERENCES public.typeofworks (id)
    NOT VALID;


ALTER TABLE public.jobadverts
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.jobadverts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.links
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.programmingskills
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.schools
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (user_id)
    NOT VALID;


ALTER TABLE public.systemworkers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.verificationcodes
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employersverificationsystemworkers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employersverificationsystemworkers
    ADD FOREIGN KEY (system_worker_id)
    REFERENCES public.systemworkers (user_id)
    NOT VALID;

END;