-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    company_name character varying(25) NOT NULL,
    phone_number character varying(15) NOT NULL,
    web_site_domain_name character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    type_of_works_id integer NOT NULL,
    nationality_id character varying(11) NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    date_of_birth date NOT NULL,
    typeofworks_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.systemworkers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    system_worker_name character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.typeofworks
(
    id integer NOT NULL,
    title character varying(25) NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email_address character varying(30) NOT NULL,
    password character varying(20) NOT NULL,
    verify_code text NOT NULL,
    verified boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (type_of_works_id)
    REFERENCES public.typeofworks (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.systemworkers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;